### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by jadekler** [jadekler/spring-security-saml-dsl#1]
Reference: https://github.com/jadekler/git-java-okta-dsl/issues/11
From @rwinch:

> Currently the project has a compile dependency on spring-boot projects. Ideally it would only have a dependency on spring-security-saml and spring-security

**Comment by jadekler** [comment]
From @jadekler:

Hey @rwinch - per issue https://github.com/jadekler/git-java-okta-dsl/issues/7, we need a couple of spring deps to override SAMLEntryPoint. Would like to find a better way to tackle that problem - we'll make that a task to look into; if there's anything on your side you can recommend we'd appreciate it too.

**Comment by rwinch** [comment]
This can be closed. I mistakenly was looking at an old version of the code that depended on Spring Boot
